### PR TITLE
xFireFoxPreference: Added resource

### LINKED ISSUE #13: xFirefoxConfiguration: A new resource to be able to manage the Firefox configuration file
### Description
Firefox has a configuration file which can be edited to handle configurations such as security hardening etc. This resource will create and edit those settings
### Proposed properties
Although the config file is in a text format, it relies on a type of key value pairing. This resource would verify that a key does/n't exist and if it does, ensure that the value is correct.
### Special considerations or limitations
The file that is created is a js.config file and will always need to start with a commented line due to the fact that the first line in js.config files are ignored

### PR DESCRIPTION
**Pull request by chasewilson**
#### Pull Request (PR) description
This Pull Request adds functionality to automate the Firefox Preferences File and set the autoconfig preferences necessary. 

#### This Pull Request (PR) fixes the following issues
-Fixes #13 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xfirefox/14)

### CODE REVIEW

**Comment by chasewilson** [comment]
@johlju I'm not exactly sure why the Build is failing and was hoping for some insight? My tests all pass locally and I need to make adjustments, I would appreciate any feedback Thanks!

**Comment by johlju** [comment]
@chasewilson I think you need to move the hashtable's (i.e `$firefoxPreference`) inside the `InModuleScope`-block.

**Comment by johlju** [comment]
Please note that due to the existence of a composite resource in this module, one test will always fail, see issue https://github.com/PowerShell/xFirefox/issues/10. Either the composite resource need to be changed to a schema.mof, or the test framework need to be changed to handle composite resources.

**Comment by chasewilson** [comment]
@johlju I had to add the hash table to each describe block. Pretty silly but works for Appveyor now. Thanks for the advice :)

**Comment by chasewilson** [comment]
@johlju Just keeping in contact. I know how busy you are. Thx

**Comment by chasewilson** [comment]
@johlju Just keeping this in view if you have time to review. Thanks :)

**Comment by johlju** [comment]
I will try to review this weekend. Thank you for reminding me! :smile:

**Comment by chasewilson** [comment]
@johlju Just following up with you 😄 Thank you for taking time to review with all your other work!

**Comment by chasewilson** [comment]
Hey @johlju just continuing to keep this on your radar :) thanks!

**Comment by chasewilson** [comment]
@johlju sorry about the silly test mistake! but it should be all good now :) Thank you for taking the time!

**Comment by johlju** [comment]
@chasewilson No worries, we all do those 😄 😉

**Comment by gaelcolas** [comment]
_Removed the abandoned label and Stale bot disabled._

@chasewilson Nearly there! If the update recommended by @johlju works, this PR should be good to get merged.

**Pull request merged**
